language: node_js
node_js:
  - "6"
addons:
  code_climate:
    repo_token: 7595ba57e96e2a7714ca9d396e1ab4b3fa4fa4d3950b15f5236c56f370b4dfd6
services:
  - postgresql
before_script:
  - psql -c 'create database acagig_test;' -U postgres
script: npm run coverage
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email:
    on_success: never
